"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient, hasSupabaseAuth } from "@/lib/client";

type Mode = "login" | "register";
type Field = "name" | "email" | "password" | "confirm";
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export default function LoginPage() {
  const router = useRouter();
  const [mode, setMode] = useState<Mode>("login");
  const [form, setForm] = useState({ name: "", email: "", password: "", confirm: "" });
  const [errors, setErrors] = useState<Partial<Record<Field, string>>>({});
  const [showPassword, setShowPassword] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState("");
  const [motion, setMotion] = useState({ x: 0, y: 0, scroll: 0 });

  useEffect(() => {
    const move = (event: PointerEvent) => setMotion((current) => ({ ...current, x: (event.clientX / innerWidth - .5) * 2, y: (event.clientY / innerHeight - .5) * 2 }));
    const scroll = () => setMotion((current) => ({ ...current, scroll: window.scrollY }));
    addEventListener("pointermove", move, { passive: true }); addEventListener("scroll", scroll, { passive: true });
    return () => { removeEventListener("pointermove", move); removeEventListener("scroll", scroll); };
  }, []);
  const update = (field: Field, value: string) => { setForm((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: undefined })); setMessage(""); };
  const switchMode = (next: Mode) => { setMode(next); setErrors({}); setMessage(""); };
  const validate = () => { const next: Partial<Record<Field, string>> = {}; if (mode === "register" && form.name.trim().length < 2) next.name = "Enter your full name."; if (!emailPattern.test(form.email)) next.email = "Enter a valid email address."; if (form.password.length < 8) next.password = "Use at least 8 characters."; if (mode === "register" && form.password !== form.confirm) next.confirm = "Passwords do not match."; setErrors(next); return !Object.keys(next).length; };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!validate()) return; if (!hasSupabaseAuth) { setMessage("Secure email access is not configured yet. Use the demo gateway to enter CodeQuest."); return; } setSubmitting(true); try { const supabase = createClient(); if (mode === "register") { const { data, error } = await supabase.auth.signUp({ email: form.email, password: form.password, options: { data: { full_name: form.name.trim() }, emailRedirectTo: `${location.origin}/` } }); if (error) throw error; if (!data.session) { switchMode("login"); setMessage("Account created. Confirm your email, then sign in."); return; } } else { const { error } = await supabase.auth.signInWithPassword({ email: form.email, password: form.password }); if (error) throw error; } router.replace("/"); } catch (error) { setMessage(error instanceof Error ? error.message : "Something went wrong. Please try again."); } finally { setSubmitting(false); } };
  const demo = () => { sessionStorage.setItem("codequest-demo-session", "true"); router.replace("/"); };
  const style = { "--x": `${motion.x * 5}deg`, "--y": `${motion.y * -5}deg`, "--scroll": `${motion.scroll * .02}px` } as React.CSSProperties;
  return <main className="nexus-page">
    <div className="nexus-glow nexus-glow--a" style={{ transform: `translate(${motion.x * 30}px, ${motion.scroll * .1}px)` }} /><div className="nexus-glow nexus-glow--b" style={{ transform: `translate(${motion.x * -40}px, ${motion.scroll * -.08}px)` }} />
    <section className="nexus-hero"><nav className="nexus-nav"><a href="/" className="nexus-logo"><span>✦</span> CODEQUEST</a><a href="/" className="nexus-exit">Explore platform ↗</a></nav><div className="nexus-copy" style={{ transform: `translateY(${motion.scroll * -.13}px)` }}><p>THE NEXT CHAPTER OF LEARNING</p><h1>Find your <em>flow state.</em></h1><strong>A focused space for ambitious developers to practice, build momentum, and make every line of code count.</strong></div><div className="nexus-orbit" aria-hidden="true" style={{ transform: `translate(${motion.x * 14}px, ${motion.scroll * -.05}px) rotateX(${62 + motion.y * 4}deg) rotateZ(${motion.scroll * .025}deg)` }}><i /><i /><i /><b /><b /><b /></div>
      <section className={`nexus-auth nexus-auth--${mode}`} style={style}><div className="nexus-auth__head"><span>◈</span><div><p>{mode === "login" ? "WELCOME BACK" : "START YOUR JOURNEY"}</p><h2>{mode === "login" ? "Enter the arena" : "Create your account"}</h2></div></div><div className="nexus-tabs"><button className={mode === "login" ? "active" : ""} onClick={() => switchMode("login")}>Login</button><button className={mode === "register" ? "active" : ""} onClick={() => switchMode("register")}>Registration</button></div><form onSubmit={(event) => void submit(event)} noValidate>{mode === "register" && <label className={errors.name ? "error" : ""}><span>FULL NAME</span><input autoComplete="name" placeholder="Alex Morgan" value={form.name} onChange={(event) => update("name", event.target.value)} />{errors.name && <small>{errors.name}</small>}</label>}<label className={errors.email ? "error" : ""}><span>EMAIL ADDRESS</span><input type="email" autoComplete="email" placeholder="you@example.com" value={form.email} onChange={(event) => update("email", event.target.value)} />{errors.email && <small>{errors.email}</small>}</label><label className={errors.password ? "error" : ""}><span>PASSWORD</span><div className="nexus-password"><input type={showPassword ? "text" : "password"} autoComplete={mode === "login" ? "current-password" : "new-password"} placeholder="At least 8 characters" value={form.password} onChange={(event) => update("password", event.target.value)} /><button type="button" onClick={() => setShowPassword((current) => !current)}>{showPassword ? "HIDE" : "SHOW"}</button></div>{errors.password && <small>{errors.password}</small>}</label>{mode === "register" && <label className={errors.confirm ? "error" : ""}><span>CONFIRM PASSWORD</span><input type={showPassword ? "text" : "password"} autoComplete="new-password" placeholder="Repeat your password" value={form.confirm} onChange={(event) => update("confirm", event.target.value)} />{errors.confirm && <small>{errors.confirm}</small>}</label>}{mode === "login" && <div className="nexus-options"><label><input type="checkbox" defaultChecked /> Remember me</label><button type="button">Forgot password?</button></div>}{message && <p className="nexus-message" role="alert">{message}</p>}<button className="nexus-submit" disabled={submitting}><span>{submitting ? "CONNECTING…" : mode === "login" ? "LOGIN TO CODEQUEST" : "CREATE MY ACCOUNT"}</span><i>→</i></button></form><div className="nexus-divider">OR</div><button className="nexus-demo" onClick={demo}><span>✦</span><span><b>Enter the demo arena</b><small>Explore CodeQuest without an account</small></span><i>→</i></button><p className="nexus-switch">{mode === "login" ? "New to CodeQuest?" : "Already a member?"} <button onClick={() => switchMode(mode === "login" ? "register" : "login")}>{mode === "login" ? "Create an account" : "Login"}</button></p></section></section>
    <section className="nexus-section nexus-intro"><div><p>A BETTER WAY TO GROW</p><h2>Small, deliberate wins<br />become real mastery.</h2></div><strong>CodeQuest turns a long road ahead into a clear, rewarding rhythm. Your next challenge is exactly where it needs to be.</strong><aside><b>10 min</b><span>is enough to protect your momentum today</span></aside></section><section className="nexus-section nexus-features"><p>DESIGNED FOR DEEP WORK</p><h2>Everything has a purpose.</h2><div>{[["⌘","Guided paths","Turn big ambitions into a focused sequence of practical lessons."],["◌","Instant practice","Build confidence through short challenges that adapt with you."],["✦","Visible progress","See your skill stack grow with every meaningful session."]].map(([icon,title,description]) => <article key={title}><span>{icon}</span><h3>{title}</h3><small>{description}</small></article>)}</div></section><section className="nexus-section nexus-play"><div className="nexus-sphere" style={{ transform: `rotateX(${motion.y * -12}deg) rotateY(${motion.x * 18 + motion.scroll * .025}deg)` }}><i /><i /><i /><b>CODE<br />QUEST</b></div><div><p>RESPONSIVE BY DESIGN</p><h2>A learning space that<br /><em>moves with you.</em></h2><strong>Every interaction carries momentum. Follow the current and make the next step yours.</strong></div></section><section className="nexus-final"><p>YOUR NEXT SESSION IS WAITING</p><h2>Turn curiosity into<br /><em>capability.</em></h2><strong>Meet yourself at the edge of what you can do.</strong><div><button onClick={() => { switchMode("login"); scrollTo({ top: 0, behavior: "smooth" }); }}>Login →</button><button onClick={() => { switchMode("register"); scrollTo({ top: 0, behavior: "smooth" }); }}>Registration →</button></div></section>
  </main>;
}
