-- Add more intermediate algorithm and problem-solving lessons to the Python roadmap.
insert into public.topics (language_id, slug, position, title, description, explanation, example_code, starter_code, task_title, task_description, expected_output, task_input)
values
  ('python', 'anagram-check', 16, 'Intermediate: Anagram Check', 'Decide whether two words use the same letters.', 'Anagrams contain exactly the same letters in a different order.\n\nSort both strings and compare the results. Equal sorted strings are anagrams.', E'first = "listen"\nsecond = "silent"\nprint(sorted(first) == sorted(second))', '', 'Check two anagrams', 'Print whether "listen" and "silent" are anagrams.', 'True', null),
  ('python', 'remove-duplicates', 17, 'Intermediate: Remove Duplicates', 'Keep unique values in their original order.', 'A set is useful for quickly checking whether you have already seen a value.\n\nScan the list from left to right and append a value only the first time you find it.', E'numbers = [3, 1, 3, 2, 1]\nunique = []\nseen = set()\n\nfor number in numbers:\n    if number not in seen:\n        unique.append(number)\n        seen.add(number)\n\nprint(unique)', '', 'Keep unique values', 'For numbers = [3, 1, 3, 2, 1], print a list of the unique values in their first-seen order.', '[3, 1, 2]', null),
  ('python', 'word-count', 18, 'Intermediate: Word Count', 'Split text into words and count them.', 'The split() method separates a sentence into a list of words wherever whitespace appears.\n\nOnce you have the list, len() gives the number of words.', E'sentence = "code is fun and code is useful"\nwords = sentence.split()\nprint(len(words))', '', 'Count the words', 'For the sentence "code is fun and code is useful", split it into words and print the word count.', '7', null),
  ('python', 'fizzbuzz', 19, 'Intermediate: FizzBuzz', 'Apply multiple conditions in the right order.', 'Check the most specific condition first: numbers divisible by both 3 and 5 must print FizzBuzz.\n\nThen check divisibility by 3 and 5 separately; otherwise print the number.', E'for number in range(1, 6):\n    if number % 15 == 0:\n        print("FizzBuzz")\n    elif number % 3 == 0:\n        print("Fizz")\n    elif number % 5 == 0:\n        print("Buzz")\n    else:\n        print(number)', '', 'FizzBuzz to five', 'Print numbers 1 through 5. Print Fizz for multiples of 3 and Buzz for multiples of 5.', E'1\n2\nFizz\n4\nBuzz', null),
  ('python', 'prime-check', 20, 'Intermediate: Prime Number Check', 'Use a loop to test possible divisors.', 'A prime number has exactly two factors: 1 and itself.\n\nTry divisors from 2 up to one less than the number. If none divide evenly, the number is prime.', E'number = 29\nis_prime = number > 1\n\nfor divisor in range(2, number):\n    if number % divisor == 0:\n        is_prime = False\n        break\n\nprint(is_prime)', '', 'Check for a prime', 'Set number to 29 and use a loop to print whether it is prime.', 'True', null),
  ('python', 'fibonacci-sequence', 21, 'Intermediate: Fibonacci Sequence', 'Build each value from the previous two.', 'Fibonacci numbers begin with 0 and 1. Every next value is the sum of the two before it.\n\nKeep two variables for the most recent values and update both during each loop.', E'first, second = 0, 1\n\nfor _ in range(6):\n    first, second = second, first + second\n\nprint(first)', '', 'Find Fibonacci number seven', 'Use a loop to print the seventh Fibonacci number when the sequence starts 0, 1, 1, 2, 3, 5, 8.', '8', null),
  ('python', 'second-largest', 22, 'Intermediate: Second Largest', 'Track more than one best value.', 'Some scans need both the largest and second-largest values seen so far.\n\nWhen a new maximum appears, move the old maximum into second place before saving the new one.', E'numbers = [10, 40, 25, 30]\nlargest = second = float("-inf")\n\nfor number in numbers:\n    if number > largest:\n        second = largest\n        largest = number\n    elif largest > number > second:\n        second = number\n\nprint(second)', '', 'Find second place', 'For numbers = [10, 40, 25, 30], use a loop to print the second-largest number.', '30', null),
  ('python', 'matrix-total', 23, 'Intermediate: Matrix Total', 'Use nested loops to visit a grid.', 'A matrix is a list of rows, where each row is itself a list.\n\nUse one loop for rows and a second loop for values in each row.', E'matrix = [[1, 2], [3, 4]]\ntotal = 0\n\nfor row in matrix:\n    for value in row:\n        total += value\n\nprint(total)', '', 'Add a matrix', 'For matrix = [[1, 2], [3, 4]], use nested loops to print the total of every value.', '10', null),
  ('python', 'caesar-shift', 24, 'Intermediate: Caesar Shift', 'Transform characters with their code points.', 'ord() turns a character into its numeric code and chr() turns a code back into a character.\n\nAdding 1 to each lowercase character shifts it one place forward in the alphabet.', E'word = "code"\nshifted = ""\n\nfor letter in word:\n    shifted += chr(ord(letter) + 1)\n\nprint(shifted)', '', 'Shift a word', 'Shift every letter in "code" forward by one position and print the new word.', 'dpef', null),
  ('python', 'balanced-brackets', 25, 'Intermediate: Balanced Brackets', 'Use a stack to match opening and closing symbols.', 'A stack stores opening brackets until their matching closing bracket appears.\n\nEach closing bracket must match the most recently opened bracket; that is why a list with append() and pop() works well.', E'text = "{[()]}"\npairs = {")": "(", "]": "[", "}": "{"}\nstack = []\nvalid = True\n\nfor character in text:\n    if character in "([{":\n        stack.append(character)\n    elif not stack or stack.pop() != pairs[character]:\n        valid = False\n        break\n\nprint(valid and not stack)', '', 'Validate brackets', 'Use a stack to print whether "{[()]}" has balanced brackets.', 'True', null)
on conflict (language_id, position) do update set
  slug = excluded.slug, title = excluded.title, description = excluded.description,
  explanation = excluded.explanation, example_code = excluded.example_code,
  starter_code = excluded.starter_code, task_title = excluded.task_title,
  task_description = excluded.task_description, expected_output = excluded.expected_output,
  task_input = excluded.task_input, updated_at = now();
