-- CodeQuest Learn: catalogue, lesson content, and per-user progress.
-- This migration intentionally uses auth.users because the current project does
-- not yet create a profiles table. It can be joined to profiles later by user_id.

create table if not exists public.learning_languages (
  id text primary key,
  name text not null,
  icon text not null,
  accent text not null,
  active boolean not null default false,
  position smallint not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  language_id text not null references public.learning_languages(id) on delete cascade,
  slug text not null,
  position smallint not null,
  title text not null,
  description text not null,
  explanation text not null,
  example_code text not null,
  starter_code text not null,
  task_title text not null,
  task_description text not null,
  expected_output text not null,
  task_input text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (language_id, position),
  unique (language_id, slug)
);

-- Compatibility columns for an existing topics table, if one is introduced by
-- another module before this migration is applied.
alter table public.topics add column if not exists starter_code text;
alter table public.topics add column if not exists task_description text;
alter table public.topics add column if not exists expected_output text;
alter table public.topics add column if not exists task_input text;

create table if not exists public.user_topic_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id bigint not null references public.topics(id) on delete cascade,
  status text not null default 'locked' check (status in ('locked', 'unlocked', 'completed')),
  completed_at timestamptz,
  primary key (user_id, topic_id),
  check ((status = 'completed' and completed_at is not null) or status <> 'completed')
);

create index if not exists user_topic_progress_user_status_idx
  on public.user_topic_progress (user_id, status);

alter table public.learning_languages enable row level security;
alter table public.topics enable row level security;
alter table public.user_topic_progress enable row level security;

drop policy if exists "Anyone can read learning languages" on public.learning_languages;
create policy "Anyone can read learning languages"
  on public.learning_languages for select to anon, authenticated using (true);

drop policy if exists "Anyone can read lesson content" on public.topics;
create policy "Anyone can read lesson content"
  on public.topics for select to anon, authenticated using (true);

drop policy if exists "Users can read their topic progress" on public.user_topic_progress;
create policy "Users can read their topic progress"
  on public.user_topic_progress for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their topic progress" on public.user_topic_progress;
create policy "Users can create their topic progress"
  on public.user_topic_progress for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their topic progress" on public.user_topic_progress;
create policy "Users can update their topic progress"
  on public.user_topic_progress for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

grant select on public.learning_languages, public.topics to anon, authenticated;
grant select, insert, update on public.user_topic_progress to authenticated;

insert into public.learning_languages (id, name, icon, accent, active, position)
values
  ('java', 'Java', 'J', '#f09a63', false, 1),
  ('python', 'Python', 'Py', '#f5c451', true, 2),
  ('javascript', 'JavaScript', 'JS', '#f4d65c', false, 3),
  ('sql', 'SQL', 'SQL', '#65b9ff', false, 4),
  ('c', 'C', 'C', '#8aa2f6', false, 5),
  ('cpp', 'C++', 'C++', '#a7a7ff', false, 6)
on conflict (id) do update set
  name = excluded.name,
  icon = excluded.icon,
  accent = excluded.accent,
  active = excluded.active,
  position = excluded.position;

insert into public.topics (
  language_id, slug, position, title, description, explanation, example_code,
  starter_code, task_title, task_description, expected_output, task_input
)
values
  ('python', 'print-statements', 1, 'Introduction to Python & Print Statements', 'Write your first line of Python and see it run.',
   'Python is a language for giving clear instructions to a computer. You write those instructions as code, then run the code to see the result.\n\nThe print() function tells Python to show something in the output area. Text needs quotation marks so Python knows it is a message, not the name of something else.',
   E'print("Hello, world!")\nprint("I am learning Python.")', E'print("Hello, CodeQuest!")', 'Send a greeting', 'Use print() to display exactly: Hello, CodeQuest!', 'Hello, CodeQuest!', null),
  ('python', 'variables-data-types', 2, 'Variables & Data Types', 'Store information in named containers.',
   'A variable is a name that points to a value. Think of it like a labeled box: you can put a value in the box and use that label later.\n\nPython has different types of values. Strings are text in quotation marks, integers are whole numbers, and booleans are true or false values.',
   E'name = "Ada"\nage = 21\nprint(name)\nprint(age)', E'age = 21\nprint(f"Age: {age}")', 'Name an age', 'Create a variable named age with the integer 21, then print exactly: Age: 21', 'Age: 21', null),
  ('python', 'basic-operators', 3, 'Basic Operators', 'Combine, compare, and test values.',
   'Operators are symbols that do work with values. Arithmetic operators such as + and * calculate new numbers, while comparison operators such as == check whether two values match.\n\nLogical operators, including and and or, let you combine true-or-false checks into more useful questions.',
   E'total = 7 * 6\nprint(total)\nprint(total == 42)', E'answer = 7 * 6\nprint(answer)', 'Make forty-two', 'Use multiplication to calculate 7 times 6 and print the result.', '42', null),
  ('python', 'strings-formatting', 4, 'Strings & String Formatting', 'Build clear messages from text and values.',
   'A string is a piece of text. You can join strings with +, but f-strings are usually easier to read when you want to include a variable inside a message.\n\nStart an f-string with the letter f before the opening quote. Put a variable name inside curly braces and Python replaces it with that variable''s value.',
   E'name = "Mina"\nmessage = f"Hello, {name}!"\nprint(message)', E'name = "Ada"\nprint(f"Hello, {name}!")', 'Personalize a hello', 'Store "Ada" in name and use an f-string to print exactly: Hello, Ada!', 'Hello, Ada!', null),
  ('python', 'conditionals', 5, 'Conditionals', 'Choose what happens with if, elif, and else.',
   'Conditionals let a program make a choice. An if statement runs its indented block only when its condition is true.\n\nUse elif for another condition and else for the remaining case. Indentation matters in Python because it marks which lines belong to each choice.',
   E'temperature = 28\nif temperature > 25:\n    print("Warm")\nelse:\n    print("Cool")', E'temperature = 28\n\nif temperature > 25:\n    print("Warm")\nelse:\n    print("Cool")', 'Choose the weather message', 'Set temperature to 28. Print Warm when it is greater than 25; otherwise print Cool.', 'Warm', null),
  ('python', 'loops', 6, 'Loops', 'Repeat useful work with for and while.',
   'A loop repeats a block of code. A for loop is handy when you know which values you want to visit, while a while loop repeats as long as a condition remains true.\n\nrange(1, 4) gives the numbers 1, 2, and 3. The final number is not included, which is a common detail to remember.',
   E'for number in range(1, 4):\n    print(number)', E'for number in range(1, 4):\n    print(number)', 'Count to three', 'Use a for loop and range() to print 1, 2, and 3, each on its own line.', E'1\n2\n3', null),
  ('python', 'lists', 7, 'Lists', 'Keep a sequence of related values together.',
   'A list stores values in a specific order. Put the values inside square brackets and separate them with commas.\n\nlen() tells you how many items a list contains. List positions start at 0, so the first item is at index 0.',
   E'fruits = ["apple", "mango", "pear"]\nprint(len(fruits))\nprint(fruits[0])', E'fruits = ["apple", "mango", "pear"]\nprint(len(fruits))', 'Count the fruit', 'Create a list named fruits with "apple", "mango", and "pear", then print how many items it has.', '3', null),
  ('python', 'dictionaries', 8, 'Dictionaries', 'Look up values by a meaningful key.',
   'A dictionary connects a key to a value. It is useful when a label, such as name or score, makes more sense than a numbered position.\n\nUse curly braces to create a dictionary and square brackets with a key to look up its value.',
   E'student = {"name": "Ada", "score": 95}\nprint(student["name"])', E'student = {"name": "Ada", "score": 95}\nprint(student["name"])', 'Read a profile', 'Create a student dictionary with name set to "Ada" and score set to 95, then print the name.', 'Ada', null),
  ('python', 'functions', 9, 'Functions', 'Give repeatable work a useful name.',
   'A function is a reusable set of instructions. Define one with def, give it a clear name, and place its body on indented lines.\n\nParameters let a function receive information. return sends a result back to the place where the function was called.',
   E'def double(number):\n    return number * 2\n\nprint(double(6))', E'def double(number):\n    return number * 2\n\nprint(double(6))', 'Double a number', 'Define double(number) so it returns the number multiplied by 2, then print double(6).', '12', null),
  ('python', 'basic-input-output', 10, 'Basic Input/Output', 'Receive text from a person and show a useful response.',
   'input() pauses a program and waits for a person to type something. The value that comes back is text, even when it looks like a number.\n\nFor this check, CodeQuest supplies the sample input Ada. Your program should use it to make a formatted welcome message.',
   E'name = input("What is your name? ")\nprint(f"Welcome, {name}!")', E'name = input("Name: ")\nprint(f"Welcome, {name}!")', 'Welcome a learner', 'Read a name with input("Name: ") and print a welcome with an f-string. The checker supplies Ada as input.', 'Name: Welcome, Ada!', E'Ada\n')
on conflict (language_id, position) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  explanation = excluded.explanation,
  example_code = excluded.example_code,
  starter_code = excluded.starter_code,
  task_title = excluded.task_title,
  task_description = excluded.task_description,
  expected_output = excluded.expected_output,
  task_input = excluded.task_input,
  updated_at = now();
